I removed the code length as hard code and moved it into a variable. I also     changed the nested for loops to be in range.
Bug: Entering an invalid code, non-int, followed by a valid code throws an
    error.

Traceback (most recent call last):
  File "c:\Users\jorda\Documents\VS Code\Mastermind-Game\mastermind.py", line 178, in <module>
    main()
  File "c:\Users\jorda\Documents\VS Code\Mastermind-Game\mastermind.py", line 50, in main
    testCode = int(getValidCode(codeLength))
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\jorda\Documents\VS Code\Mastermind-Game\mastermind.py", line 95, in getValidCode
    return code
           ^^^^
UnboundLocalError: cannot access local variable 'code' where it is not associated with a value

Possibly because the Try/Catch does not assign a value to the variable code.